"""Add ai_analysis and ai_advice

Revision ID: 013fc7f0c470
Revises: fb24506a68d8
Create Date: 2026-05-26 13:06:43.722415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013fc7f0c470'
down_revision = 'fb24506a68d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_analysis', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_advice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('ai_advice')
        batch_op.drop_column('ai_analysis')

    # ### end Alembic commands ###
