"""add_activity_categories

Revision ID: 26187660e663
Revises: 65f2d31d159e
Create Date: 2026-05-29 16:49:25.260503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26187660e663'
down_revision = '65f2d31d159e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###
