"""Add password_hash

Revision ID: 26df509df234
Revises: b201997d9784
Create Date: 2026-05-28 23:46:34.692649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26df509df234'
down_revision = 'b201997d9784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
