"""add_sleep_master_badge

Revision ID: 65f2d31d159e
Revises: f0bf9a7ee4c1
Create Date: 2026-05-29 16:32:49.837543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f2d31d159e'
down_revision = 'f0bf9a7ee4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_sleep_master_badge', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_sleep_master_badge')

    # ### end Alembic commands ###
