"""Add ai sentiment score keywords

Revision ID: 68b9026d01ae
Revises: 763cace8f170
Create Date: 2026-05-26 15:25:22.623124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b9026d01ae'
down_revision = '763cace8f170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_sentiment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_keywords', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('ai_keywords')
        batch_op.drop_column('ai_score')
        batch_op.drop_column('ai_sentiment')

    # ### end Alembic commands ###
