"""Add sleep, stress, activities

Revision ID: 763cace8f170
Revises: 013fc7f0c470
Create Date: 2026-05-26 15:08:04.047017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763cace8f170'
down_revision = '013fc7f0c470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stress_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activities', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('activities')
        batch_op.drop_column('stress_level')
        batch_op.drop_column('sleep_hours')

    # ### end Alembic commands ###
