"""Auto-migration on startup

Revision ID: 95ddd3d4cc8c
Revises: 9a8cd6ee3ba6
Create Date: 2026-05-30 00:15:03.339083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ddd3d4cc8c'
down_revision = '9a8cd6ee3ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.alter_column('mini_journal',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.alter_column('mini_journal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
