"""Auto-migration on startup

Revision ID: 9a8cd6ee3ba6
Revises: e741e3fabac8
Create Date: 2026-05-29 23:33:47.138904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8cd6ee3ba6'
down_revision = 'e741e3fabac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mini_journal', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('free_writing', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('free_writing')
        batch_op.drop_column('mini_journal')

    # ### end Alembic commands ###
