"""Add sleep tracking fields

Revision ID: a43df3e1c837
Revises: f21200adca1b
Create Date: 2026-05-29 15:54:30.038953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43df3e1c837'
down_revision = 'f21200adca1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_entry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_entry_date')
        batch_op.drop_column('streak_count')

    # ### end Alembic commands ###
