"""add_lifestyle_metrics

Revision ID: f0bf9a7ee4c1
Revises: a43df3e1c837
Create Date: 2026-05-29 16:26:15.812169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bf9a7ee4c1'
down_revision = 'a43df3e1c837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_work_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('social_interaction_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weather_condition', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('weather_condition')
        batch_op.drop_column('social_interaction_score')
        batch_op.drop_column('is_work_day')

    # ### end Alembic commands ###
