"""Add sleep fields

Revision ID: f21200adca1b
Revises: f7973c7a8cb4
Create Date: 2026-05-29 15:13:50.269014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21200adca1b'
down_revision = 'f7973c7a8cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedtime', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('wakeup_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('sleep_quality', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dream_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('caffeine_intake', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('screen_time', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_entry_date')
        batch_op.drop_column('streak_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_entry_date', sa.DATE(), nullable=True))

    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('screen_time')
        batch_op.drop_column('caffeine_intake')
        batch_op.drop_column('dream_note')
        batch_op.drop_column('sleep_quality')
        batch_op.drop_column('wakeup_time')
        batch_op.drop_column('bedtime')

    # ### end Alembic commands ###
