"""empty message

Revision ID: f7973c7a8cb4
Revises: 26df509df234
Create Date: 2026-05-29 14:34:54.205223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7973c7a8cb4'
down_revision = '26df509df234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_entry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_entry_date')
        batch_op.drop_column('streak_count')

    # ### end Alembic commands ###
