"""add mood entry

Revision ID: fb24506a68d8
Revises: 7455b9644935
Create Date: 2026-05-25 11:28:21.673400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb24506a68d8'
down_revision = '7455b9644935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_entry_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_entry_timestamp'))

    op.drop_table('mood_entry')
    # ### end Alembic commands ###
